name: tomcat-prime-number

on:
  push:
    branches: [ main ]
    paths:
      - 'energyMeter.py'
      - 'prime_number.robot'
      - 'SUTs/prime_numbers_java/**'
      - '.github/workflows/tomcat-test-and-release-prime.yml'
      - 'test_energyMeter.py'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      CATALINA_HOME: ${{ github.workspace }}/apache-tomcat-10.1.18

    steps:
    - uses: actions/checkout@v2

    - name: Debug git information
      run: |
        git status --verbose
        git log -n 5 --oneline

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil robotframework robotframework-browser

    - name: Install Robot Framework Browser
      run: |
        rfbrowser init

    - name: Run Python unit tests
      run: |
        python -m unittest discover -s .

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Build with Maven
      run: |
        cd SUTs/prime_numbers_java
        mvn package

    - name: Download and Set up Tomcat
      run: |
        wget https://downloads.apache.org/tomcat/tomcat-10/v10.1.18/bin/apache-tomcat-10.1.18.tar.gz
        tar xzvf apache-tomcat-10.1.18.tar.gz

    - name: Deploy to Tomcat
      run: |
        cp SUTs/prime_numbers_java/target/prime_numbers_java.war $CATALINA_HOME/webapps/
        sh $CATALINA_HOME/bin/startup.sh

    - name: Print Tomcat logs
      run: |
        cat $CATALINA_HOME/logs/catalina.out


    - name: Run Robot Framework tests
      run: robot --variable HEADLESS:True --outputdir results --listener energyMeter.py --variable SERVER:tomcat prime_number.robot

    - name: Upload Robot Framework test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: robot-results
        path: results
